name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          TEST_USER_EMAIL=${{ secrets.TEST_USER_LOGIN }} \
          TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }} \
          MAIN_URL=https://gotaskme.com \
          BASE_URL=https://app.gotaskme.com \
          npx playwright test --project=chromium
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: report
          path: playwright-report/
          retention-days: 7